site_name: Coco Loco - Guias
pages: 
  - Home: index.md
  - Normal / Heróico:
    - Antorus: guia/antorus/index.md
    - ToS:
      - Avatar Caído: guia/tos/avatar_caido.md
      - Kil'jaeden: guia/tos/kiljaeden.md
extra_javascript: 
  - //wow.zamimg.com/widgets/power.js
  - js/wowhead.js
theme: 
  name: 'material'
